DROP TABLE IF EXISTS "USER","BOOK","COLLECT";

CREATE TABLE "USER" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "BOOK" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" text NOT NULL,
  "cover" varchar NOT NULL,
  "author" text NOT NULL,
  "description" varchar NOT NULL,
  "publish_year" year NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "COLLECT" (
  "user_id" integer,
  "book_id" integer,
  "status" varchar(50) NOT NULL
);

ALTER TABLE "COLLECT" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("id");

ALTER TABLE "COLLECT" ADD FOREIGN KEY ("book_id") REFERENCES "BOOK" ("id");
