DROP TABLE IF EXISTS "USER","BOOK","COLLECT", "THREAD", "COMMENT";

CREATE TABLE "USER" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "name" varchar(100) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "BOOK" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" TEXT NOT NULL,
  "cover" varchar NOT NULL,
  "author" TEXT NOT NULL,
  "description" text NOT NULL,
  "publish_year" SMALLINT NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "COLLECT" (
  "user_id" integer,
  "book_id" integer,
  "status" varchar(50) NOT NULL
);

CREATE TABLE "THREAD"(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar NOT NULL,
  "body" TEXT NOT NULL,
  "user_id" integer NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "COMMENT" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "body" text NOT NULL,
  "user_id" integer NOT NULL,
  "thread_id" integer NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "COLLECT" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("id") ON DELETE CASCADE;

ALTER TABLE "COLLECT" ADD FOREIGN KEY ("book_id") REFERENCES "BOOK" ("id") ON DELETE CASCADE;

ALTER TABLE "THREAD" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("id") ON DELETE CASCADE;

ALTER TABLE "COMMENT" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("id") ON DELETE CASCADE;

ALTER TABLE "COMMENT" ADD FOREIGN KEY ("thread_id") REFERENCES "THREAD" ("id") ON DELETE CASCADE;
